---
- name: installing boundary dependencies
  package:
    name:
      - unzip
      - curl
    state: present

- name: creating boundary group
  group:
    name: '{{ boundary_group }}'
    system: yes
  when: boundary_create_account

- name: creating boundary user
  user:
    name: '{{ boundary_user }}'
    home: '{{ boundary_home_directory }}'
    group: '{{ boundary_group }}'
    shell: /bin/false
    system: yes
  when: boundary_create_account

- name: creating boundary directories
  file:
    state: directory
    path: '{{ item }}'
    owner: '{{ boundary_user }}'
    group: '{{ boundary_group }}'
    mode: '0750'
  with_items:
  - '{{ boundary_home_directory }}'
  - '{{ boundary_data_directory }}'
  - '{{ boundary_install_directory }}'

- name: installing boundary binary
  unarchive:
    src: '{{ boundary_download }}'
    dest: '{{ boundary_install_directory }}'
    owner: '{{ boundary_user }}'
    group: '{{ boundary_group }}'
    remote_src: yes
    mode: '0770'
  tags:
    - install

