---
- name: add Hashicorp repo
  command: "yum-config-manager --add-repo=yum-config-manager --add-repo {{ boundary_yum_repo }}"
  args:
    creates: /etc/yum.repos.d/hashicorp.repo
  become: true

- name: install Boundary
  yum:
    name: "boundary-{{ boundary_version }}"
    update_cache: true
  become: true
