---
- name: Prepare
  hosts: all
  tasks:
    - name: Update Apt
      command: "apt-get update"
      when: ansible_os_family == 'Debian'

    - name: Install GnuPG
      package:
        name: gnupg
