---
- name: installing boundary dependencies
  package:
    name:
      - unzip
      - curl
    state: present

- name: creating boundary group
  group:
    name: '{{ boundary_group }}'
    system: yes
  when: boundary_create_account

- name: creating boundary user
  user:
    name: '{{ boundary_user }}'
    home: '{{ boundary_home_directory }}'
    group: '{{ boundary_group }}'
    shell: /bin/false
    system: yes
  when: boundary_create_account

- name: creating boundary directories
  file:
    state: directory
    path: '{{ item }}'
    owner: '{{ boundary_user }}'
    group: '{{ boundary_group }}'
    mode: '0750'
  with_items:
  - '{{ boundary_home_directory }}'
  - '{{ boundary_data_directory }}'
  - '{{ boundary_install_directory }}'

- name: installing boundary binary
  unarchive:
    src: '{{ boundary_download }}'
    dest: '{{ boundary_install_directory }}'
    owner: '{{ boundary_user }}'
    group: '{{ boundary_group }}'
    remote_src: yes
    mode: '0770'
  notify:
    - restart boundary

- name: templating out boundary worker configuration
  template:
    src: boundary-worker.hcl.j2
    dest: '{{ boundary_worker_file }}'
    owner: '{{ boundary_user }}'
    group: '{{ boundary_group }}'
    mode: '0640'
  when: boundary_node_type == 'worker'
  notify:
    - restart boundary

- name: templating out boundary controller configuration
  template:
    src: boundary-controller.hcl.j2
    dest: '{{ boundary_controller_file }}'
    owner: '{{ boundary_user }}'
    group: '{{ boundary_group }}'
    mode: '0640'
  when: boundary_node_type == 'controller'
  notify:
    - restart boundary

- name: templating out systemd script
  template:
    src: boundary.systemd.j2
    dest: /etc/systemd/system/boundary.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload boundary daemon

- name: initializing database for boundary
  shell: '{{ boundary_install_directory }}/boundary database init -config {{ boundary_controller_file }} > {{ boundary_data_directory }}/init.txt'
  run_once: yes

- name: starting and enabling boundary
  systemd:
    name: boundary
    enabled: yes
    state: started